services:
  - type: web
    name: WhatsBixby
    repo: https://github.com/c-o-d-e-xx/WhatsBixby.git
    branch: master
    runtime: docker
    dockerfilePath: lib/Dockerfile
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
        required: true
    plan: free
